spring:
  application:
    name: learn-english-words-bot
  datasource:
    url: jdbc:postgresql://188.225.44.33:5432/default_db
    username: gen_user
    password: 2q9dle70r
    hikari:
      maximum-pool-size: 8
      max-lifetime: 300000 #5 минут
      connection-timeout: 10000
  liquibase:
    enabled: true
    change-log: classpath:db/scripts/changelog-master.xml
    url: jdbc:postgresql://188.225.44.33:5432/default_db
    user: gen_user
    password: 2q9dle70r
    liquibase-schema: "public"
    default-schema: "public"
  jackson:
    default-property-inclusion: non_null

learn-english-words-bot:
  bot:
    name: "NessieEnglishBot"
    token: "1609208756:AAGDVjdSRN7oXwMFbgg0eP-82o0iCIhMmPU"
  settings:
    words-page-size: 10
    channel-id: -1001573779809
  scheduler:
    send-words-cron: "0 */30 * * * *"
    send-quiz-cron: "0 */50 * * * *"
    channel-send-words-cron: "0 */3 * * * *"
    channel-send-quiz-words: "0 */5 * * * *"
  messages:
    start-learning: "Отлично, давай начнем, несколько раз в день я буду присылать тебе слова с переводом и произношением, постарайся их запомнить, потому что по мере обучения я буду присылать опросы для проверки знаний😏\n Вот первый список слов:"
    stop-learning: "Хорошо, я больше не буду присылать тебе английские слова \uD83D\uDE14, когда захочешь - возвращайся (/start)"
    resume-learning: "Отлично, давай продолжим твое обучение! \uD83D\uDE0A"
    learning-already-started: "Ты уже начал(а) своё обучение! \uD83D\uDE0A"
    unknown-command: "Неизвестная команда\uD83E\uDD14"
    info: "Я Несси\uD83D\uDC0D, особенный бот для изучения английских слов\uD83E\uDD13 \n\n
           В чем особенность❓\n
           Согласно ислледованиям авторов словарей Macmillan, Longman, Oxford есть определенный набор слов,
           которые покрывают 80-90% английской речи, зная их вы сможете свободно разговаривать на английском на общие темы и читать статьи (при условии понимания остальных аспектов языка).\n
           В моей базе имеется около 5 тыс. часто употребляемых слов (по данным Oxford Learner's Dictionaries), и я помогу постепенно выучить эти слова\uD83D\uDE0E  \n\n
           Для кого?\n
           Как для начинающих изучать английский язык, так и для владеющих языком людей с целью освежить, закрепить свои знания.\n
           От вас нужно на ежедневной основе уделять мне не более 10 минут в день."
    commands: "/start - начать обучение\n
    /stop - приостановить обучение\n
    /words - получить слова\n
    /settings - настройки\n
    /full_access - полный доступ к функционалу\n
    /info - информация о боте\n
    /donate - поддержать проект\n
    /support - поддержка, обратная связь"
    support: "@NessieSupport - напишите сюда ваш вопрос или предложение🙂"
    donate: "Вы можете поддержать работу бота любой комфортной для вас суммой, спасибо!🥺"
    words-full-access: "Безлимитный доступ к словам доступен только пользователям, оформившим полный доступ - \n /full_access"
  stickers:
    thumbs_up: "CAACAgIAAxkBAAIC92EdNALFBPjcBjLvOjeb56JNIzcRAALyEgAC8nrgSPw0rHeQ9KSjIAQ"
    hmm: "CAACAgIAAxkBAAIC_2EdNfK4gRpjRWAS5_04KYCyyIieAAL1EQACOK_gSFhUIJ1XZu8dIAQ"
    kindly: "CAACAgIAAxkBAAIC_WEdNeBYVmvsARfK_olPJWTVgdozAALBEAACG6LhSJ2dl5segeANIAQ"
    wink: "CAACAgIAAxkBAAIDAWEdNj5ZVEX_5fsDHKJUj22CD2maAAJREAACWOfhSOOBvr0yhaojIAQ"
