spring:
  application:
    name: learn-english-words-bot
  datasource:
    url: jdbc:postgresql://188.225.44.33:5432/default_db
    username:
    password:
    hikari:
      maximum-pool-size: 8
      max-lifetime: 300000 #5 минут
      connection-timeout: 10000
  liquibase:
    enabled: true
    change-log: classpath:db/scripts/changelog-master.xml
    url: jdbc:postgresql://188.225.44.33:5432/default_db
    user:
    password:
    liquibase-schema: "public"
    default-schema: "public"
  jackson:
    default-property-inclusion: non_null

learn-english-words-bot:
  bot:
    name: "NessieEnglishBot"
    token:
  settings:
    words-page-size: 10
    quiz-page-size: 5
    test-limit-words-page-count: 4
    quiz-start-words-count: 200
  scheduler:
    send-words-cron: "0 0 9,12,15,18 ? * *"
    send-quiz-cron: "0 0 11,14,17,20 ? * *"
  messages:
    start-learning: "Отлично, давай начнем, несколько раз в день я буду присылать тебе слова с переводом и произношением, постарайся их запомнить, потому что по мере обучения я буду присылать опросы для проверки знаний😏\n Вот первый список слов:"
    stop-learning: "Хорошо, я больше не буду присылать тебе английские слова \uD83D\uDE14, когда захочешь - возвращайся (/start)"
    resume-learning: "Отлично, давай продолжим твое обучение! Я присылаю слова несколько раз в день в автоматическом режиме \uD83D\uDE0A"
    learning-already-started: "Ты уже начал(а) своё обучение! Я присылаю слова несколько раз в день в автоматическом режиме \uD83D\uDE0A"
    all-words-learned: "Похоже, ты уже изучил(а) все английские слова, которые я знаю, если хочешь, то можем начать сначала \uD83D\uDE42 (/start)"
    full-access-already-purchased: "У тебя уже оформлен полный доступ к функционалу, продолжай обучение\uD83D\uDE0A"
    settings: "Настройки"
    unknown-command: "Неизвестная команда\uD83E\uDD14"
    info: "Я Несси\uD83D\uDC0D, особенный бот для изучения английских слов\uD83E\uDD13 \n\n
           В чем особенность❓\n
           Согласно исследованиям авторов словарей Macmillan, Longman, Oxford есть определенный набор слов,
           которые покрывают 80-90% английской речи, зная их вы сможете свободно разговаривать на английском на общие темы и читать статьи (при условии понимания остальных аспектов языка).\n
           В моей базе имеется около 5 тыс. часто употребляемых слов (по данным Oxford Learner's Dictionaries), и я помогу постепенно выучить эти слова\uD83D\uDE0E  \n\n
           Для кого❓\n
           Как для начинающих изучать английский язык, так и для владеющих языком людей с целью освежить, закрепить свои знания.\n
           Наборы слов и опросы для проверки знаний присылаются несколько раз в день в автоматическом режиме. \n
           От вас нужно на ежедневной основе уделять мне не более 20 минут в день.\n\n
           Полный доступ к фунционалу❗️\n
           На время ознакомительного периода предлагается 2 дня, после чего для дальнейшего использования бота необходимо оформить полный доступ к функционалу (299 RUB, /full_access)."
    commands: "/start - начать обучение\n
    /stop - приостановить обучение\n
    /settings - настройки\n
    /full_access - полный доступ к функционалу\n
    /info - информация о боте\n
    /support - поддержка, обратная связь\n
    /donate - поддержать проект"
    support: "@NessieSupport - напишите сюда ваш вопрос или предложение🙂"
    donate: "Вы можете поддержать работу бота любой комфортной для вас суммой, спасибо!🥺"
    success-full-access-payment: "Полный доступ успешно оформлен, спасибо!"
    success-donate-payment: "Спасибо, что поддерживаете проект и помогаете ему развиваться!🥺"
    words-full-access: "Безлимитный доступ к словам доступен только пользователям, оформившим полный доступ - \n /full_access"
    test-period-over: "Похоже, твой тестовый период закончился, для дальнейшего использования бота необходимо приобрести доступ к полному функционалу. \n
                      @NessieSupport - если возникнут какие-то вопросы🙂"
  stickers:
    thumbs_up: "CAACAgIAAxkBAAIC92EdNALFBPjcBjLvOjeb56JNIzcRAALyEgAC8nrgSPw0rHeQ9KSjIAQ"
    hmm: "CAACAgIAAxkBAAIC_2EdNfK4gRpjRWAS5_04KYCyyIieAAL1EQACOK_gSFhUIJ1XZu8dIAQ"
    kindly: "CAACAgIAAxkBAAIC_WEdNeBYVmvsARfK_olPJWTVgdozAALBEAACG6LhSJ2dl5segeANIAQ"
    wink: "CAACAgIAAxkBAAIDAWEdNj5ZVEX_5fsDHKJUj22CD2maAAJREAACWOfhSOOBvr0yhaojIAQ"
  payment:
    provider-token:
    full-access:
      title: "Полный доступ"
      description: "Полный доступ к функционалу Несси"
      currency: "RUB"
      amount: 29900
    donate:
      title: "Поддержать проект"
      description: "На развитие и поддержку проекта"
      currency: "RUB"
      amounts:
        - 9900
        - 19900
        - 29900
        - 39900